# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    #Product
    App\Product\Application\:
        resource: '../src/Product/Application'

    App\Product\Domain\:
        resource: '../src/Product/Domain'

    App\Product\Infrastructure\:
        resource: '../src/Product/Infrastructure'

    App\Product\UI\:
        resource: '../src/Product/UI'

    App\Product\UI\Controller\:
        resource: '../src/Product/UI/Controller'
        tags: [ 'controller.service_arguments' ]

    App\Product\Application\Handler\Command\:
        resource: '../src/Product/Application/Handler/Command/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: command.bus } ]

    App\Product\Application\Handler\Query\:
        resource: '../src/Product/Application/Handler/Query/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: query.bus } ]

    #Blog
    App\Blog\Application\:
        resource: '../src/Blog/Application'

    App\Blog\Domain\:
        resource: '../src/Blog/Domain'

    App\Blog\Infrastructure\:
        resource: '../src/Blog/Infrastructure'

    App\Blog\UI\:
        resource: '../src/Blog/UI'

    App\Blog\UI\Controller\:
        resource: '../src/Blog/UI/Controller'
        tags: [ 'controller.service_arguments' ]

    App\Blog\Application\Handler\Command\:
        resource: '../src/Blog/Application/Handler/Command/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: command.bus } ]

    App\Blog\Application\Handler\Query\:
        resource: '../src/Blog/Application/Handler/Query/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: query.bus } ]

    #User
    App\User\Application\:
        resource: '../src/User/Application'

    App\User\Domain\:
        resource: '../src/User/Domain'

    App\User\Infrastructure\:
        resource: '../src/User/Infrastructure'

    App\User\UI\:
        resource: '../src/User/UI'

    App\User\UI\Controller\:
        resource: '../src/User/UI/Controller'
        tags: [ 'controller.service_arguments' ]

    App\User\Application\Handler\Command\:
        resource: '../src/User/Application/Handler/Command/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: command.bus } ]

    App\User\Application\Handler\Query\:
        resource: '../src/User/Application/Handler/Query/'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: query.bus } ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
